# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/softchord_main_window.ui'
#
# Created: Sat Jan 12 14:09:06 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1087, 809)
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "softChord Editor", None))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0,0,0,0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Songs in the current songbook:", None))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Filter:", None))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_7.addWidget(self.label_2)
        self.song_filter_ef = QtWidgets.QLineEdit(self.layoutWidget)
        self.song_filter_ef.setObjectName(_fromUtf8("song_filter_ef"))
        self.horizontalLayout_7.addWidget(self.song_filter_ef)
        self.clear_filter_button = QtWidgets.QToolButton(self.layoutWidget)
        self.clear_filter_button.setText(QtWidgets.QApplication.translate("MainWindow", "x", None))
        self.clear_filter_button.setObjectName(_fromUtf8("clear_filter_button"))
        self.horizontalLayout_7.addWidget(self.clear_filter_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.songs_view = QtWidgets.QTableView(self.layoutWidget)
        self.songs_view.setMinimumSize(QtCore.QSize(100, 80))
        self.songs_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.songs_view.setObjectName(_fromUtf8("songs_view"))
        self.verticalLayout_3.addWidget(self.songs_view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.new_song_button = QtWidgets.QPushButton(self.layoutWidget)
        self.new_song_button.setText(QtWidgets.QApplication.translate("MainWindow", "New Song", None))
        self.new_song_button.setObjectName(_fromUtf8("new_song_button"))
        self.horizontalLayout_2.addWidget(self.new_song_button)
        self.delete_song_button = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_song_button.setText(QtWidgets.QApplication.translate("MainWindow", "Delete selected", None))
        self.delete_song_button.setObjectName(_fromUtf8("delete_song_button"))
        self.horizontalLayout_2.addWidget(self.delete_song_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(0,0,0,0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Current song:", None))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Number:", None))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.song_num_ef = QtWidgets.QLineEdit(self.layoutWidget1)
        self.song_num_ef.setMaximumSize(QtCore.QSize(50, 16777215))
        self.song_num_ef.setObjectName(_fromUtf8("song_num_ef"))
        self.horizontalLayout.addWidget(self.song_num_ef)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Title:", None))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.song_title_ef = QtWidgets.QLineEdit(self.layoutWidget1)
        self.song_title_ef.setObjectName(_fromUtf8("song_title_ef"))
        self.horizontalLayout.addWidget(self.song_title_ef)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Key:", None))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.song_key_menu = QtWidgets.QComboBox(self.layoutWidget1)
        self.song_key_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.song_key_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.song_key_menu.setObjectName(_fromUtf8("song_key_menu"))
        self.horizontalLayout_4.addWidget(self.song_key_menu)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Alternative key:", None))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.song_alt_key_menu = QtWidgets.QComboBox(self.layoutWidget1)
        self.song_alt_key_menu.setMinimumSize(QtCore.QSize(50, 0))
        self.song_alt_key_menu.setMaximumSize(QtCore.QSize(60, 16777215))
        self.song_alt_key_menu.setObjectName(_fromUtf8("song_alt_key_menu"))
        self.horizontalLayout_4.addWidget(self.song_alt_key_menu)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Notes:", None))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.song_subtitle_ef = QtWidgets.QLineEdit(self.layoutWidget1)
        self.song_subtitle_ef.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.song_subtitle_ef.setObjectName(_fromUtf8("song_subtitle_ef"))
        self.horizontalLayout_4.addWidget(self.song_subtitle_ef)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chord_editor_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.chord_editor_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter chord editing mode (⌘K).   This mode allows you to modify chords for the current song.</p></body></html>", None))
        self.chord_editor_button.setText(QtWidgets.QApplication.translate("MainWindow", "Edit Chords", None))
        self.chord_editor_button.setObjectName(_fromUtf8("chord_editor_button"))
        self.horizontalLayout_6.addWidget(self.chord_editor_button)
        self.lyric_editor_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.lyric_editor_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter lyric editing mode (⌘L).   This mode lets you modify the song text.</p></body></html>", None))
        self.lyric_editor_button.setText(QtWidgets.QApplication.translate("MainWindow", "Edit Text", None))
        self.lyric_editor_button.setObjectName(_fromUtf8("lyric_editor_button"))
        self.horizontalLayout_6.addWidget(self.lyric_editor_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Transpose:", None))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.transpose_down_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.transpose_down_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Transpose the whole song one half-step down.", None))
        self.transpose_down_button.setText(QtWidgets.QApplication.translate("MainWindow", "Down", None))
        self.transpose_down_button.setObjectName(_fromUtf8("transpose_down_button"))
        self.horizontalLayout_6.addWidget(self.transpose_down_button)
        self.transpose_up_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.transpose_up_button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Transpose the whole song one half-step up.", None))
        self.transpose_up_button.setText(QtWidgets.QApplication.translate("MainWindow", "Up", None))
        self.transpose_up_button.setObjectName(_fromUtf8("transpose_up_button"))
        self.horizontalLayout_6.addWidget(self.transpose_up_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.chords_editor_label = QtWidgets.QLabel(self.layoutWidget1)
        self.chords_editor_label.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">To add a new chord:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Press on a lyrics letter to select it, then press one of the following keys: A, B, C, D, E, F, or G.  To assign a sharp or a flat, press the &quot;Up&quot; or &quot;Down&quot; key afterwards to &quot;transpose&quot; the chord.  To create a minor chord, press the &quot;M&quot; key.  To create advanced chords, double-click on the created chord (a dialog box will open).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">To edit a chord:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Click on the chord to select it, then press &quot;M&quot; to toggle major/minor, press another letter to assign a different note, or press &quot;Up&quot; or &quot;Down&quot; keys to transpose it. Double-click on the chord for advanced modifications.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">To move a chord:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Click on the chord to select it, and then use the &quot;Left&quot; or &quot;Right&quot; keys to move it relative to the lyrics below it. Alternatively you can simply drag it to the new place.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">To duplicate a chord:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">While holding the &quot;Option&quot; key, click and drag the chord. Alternatively you can use copy-and-paste.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">To delete a chord:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Click on the chord to select it, and press the &quot;Delete&quot; key.</span></p></body></html>", None))
        self.chords_editor_label.setText(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Edit chords of the selected song: </span> <span style=\" font-style:italic;\">(Hover mouse here for help)</span></p></body></html>", None))
        self.chords_editor_label.setWordWrap(True)
        self.chords_editor_label.setObjectName(_fromUtf8("chords_editor_label"))
        self.verticalLayout.addWidget(self.chords_editor_label)
        self.lyrics_editor_label = QtWidgets.QLabel(self.layoutWidget1)
        self.lyrics_editor_label.setToolTip(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">When in lyric editing mode, you can modify the text (lyrics) of the song.  As text is moved/added/removed, chords get moved automatically to follow their letters.   Remember to go back into the chord editor mode when you need modify chords.</span></p></body></html>", None))
        self.lyrics_editor_label.setText(QtWidgets.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Edit lyrics of the selected song: </span> <span style=\" font-style:italic;\">(Hover mouse here for help)</span></p></body></html>", None))
        self.lyrics_editor_label.setWordWrap(True)
        self.lyrics_editor_label.setObjectName(_fromUtf8("lyrics_editor_label"))
        self.verticalLayout.addWidget(self.lyrics_editor_label)
        self.lyric_editor_layout = QtWidgets.QVBoxLayout()
        self.lyric_editor_layout.setObjectName(_fromUtf8("lyric_editor_layout"))
        self.chord_scroll_area = QtWidgets.QScrollArea(self.layoutWidget1)
        self.chord_scroll_area.setMinimumSize(QtCore.QSize(100, 100))
        self.chord_scroll_area.setToolTip(_fromUtf8(""))
        self.chord_scroll_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chord_scroll_area.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.chord_scroll_area.setWidgetResizable(True)
        self.chord_scroll_area.setObjectName(_fromUtf8("chord_scroll_area"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 651, 558))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.chord_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.lyric_editor_layout.addWidget(self.chord_scroll_area)
        self.verticalLayout.addLayout(self.lyric_editor_layout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.zoom_out_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.zoom_out_button.setText(QtWidgets.QApplication.translate("MainWindow", "-", None))
        self.zoom_out_button.setObjectName(_fromUtf8("zoom_out_button"))
        self.horizontalLayout_3.addWidget(self.zoom_out_button)
        self.zoom_slider = QtWidgets.QSlider(self.layoutWidget1)
        self.zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_slider.setObjectName(_fromUtf8("zoom_slider"))
        self.horizontalLayout_3.addWidget(self.zoom_slider)
        self.zoom_in_button = QtWidgets.QToolButton(self.layoutWidget1)
        self.zoom_in_button.setText(QtWidgets.QApplication.translate("MainWindow", "+", None))
        self.zoom_in_button.setObjectName(_fromUtf8("zoom_in_button"))
        self.horizontalLayout_3.addWidget(self.zoom_in_button)
        self.zoom_label = QtWidgets.QLabel(self.layoutWidget1)
        self.zoom_label.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom: 100%", None))
        self.zoom_label.setObjectName(_fromUtf8("zoom_label"))
        self.horizontalLayout_3.addWidget(self.zoom_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSong = QtWidgets.QMenu(self.menubar)
        self.menuSong.setTitle(QtWidgets.QApplication.translate("MainWindow", "Song", None))
        self.menuSong.setObjectName(_fromUtf8("menuSong"))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None))
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edit", None))
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewSong = QtWidgets.QAction(MainWindow)
        self.actionNewSong.setText(QtWidgets.QApplication.translate("MainWindow", "New Song", None))
        self.actionNewSong.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None))
        self.actionNewSong.setObjectName(_fromUtf8("actionNewSong"))
        self.actionDeleteSong = QtWidgets.QAction(MainWindow)
        self.actionDeleteSong.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None))
        self.actionDeleteSong.setObjectName(_fromUtf8("actionDeleteSong"))
        self.actionExportText = QtWidgets.QAction(MainWindow)
        self.actionExportText.setText(QtWidgets.QApplication.translate("MainWindow", "Export To TEXT...", None))
        self.actionExportText.setObjectName(_fromUtf8("actionExportText"))
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setText(QtWidgets.QApplication.translate("MainWindow", "Print...", None))
        self.actionPrint.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+P", None))
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionLyricsFont = QtWidgets.QAction(MainWindow)
        self.actionLyricsFont.setText(QtWidgets.QApplication.translate("MainWindow", "Lyrics Font...", None))
        self.actionLyricsFont.setObjectName(_fromUtf8("actionLyricsFont"))
        self.actionChordsFont = QtWidgets.QAction(MainWindow)
        self.actionChordsFont.setText(QtWidgets.QApplication.translate("MainWindow", "Chords Font...", None))
        self.actionChordsFont.setObjectName(_fromUtf8("actionChordsFont"))
        self.actionImportText = QtWidgets.QAction(MainWindow)
        self.actionImportText.setText(QtWidgets.QApplication.translate("MainWindow", "Import From TEXT...", None))
        self.actionImportText.setObjectName(_fromUtf8("actionImportText"))
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None))
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionCloseSongbook = QtWidgets.QAction(MainWindow)
        self.actionCloseSongbook.setText(QtWidgets.QApplication.translate("MainWindow", "Close Songbook", None))
        self.actionCloseSongbook.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None))
        self.actionCloseSongbook.setObjectName(_fromUtf8("actionCloseSongbook"))
        self.actionOpenSongbook = QtWidgets.QAction(MainWindow)
        self.actionOpenSongbook.setText(QtWidgets.QApplication.translate("MainWindow", "Open Songbook...", None))
        self.actionOpenSongbook.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None))
        self.actionOpenSongbook.setObjectName(_fromUtf8("actionOpenSongbook"))
        self.actionNewSongbook = QtWidgets.QAction(MainWindow)
        self.actionNewSongbook.setText(QtWidgets.QApplication.translate("MainWindow", "New Songbook...", None))
        self.actionNewSongbook.setObjectName(_fromUtf8("actionNewSongbook"))
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setText(QtWidgets.QApplication.translate("MainWindow", "Undo", None))
        self.actionUndo.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Z", None))
        self.actionUndo.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setText(QtWidgets.QApplication.translate("MainWindow", "Redo", None))
        self.actionRedo.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None))
        self.actionRedo.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.actionSaveSongbook = QtWidgets.QAction(MainWindow)
        self.actionSaveSongbook.setText(QtWidgets.QApplication.translate("MainWindow", "Save Songbook As...", None))
        self.actionSaveSongbook.setObjectName(_fromUtf8("actionSaveSongbook"))
        self.actionExportMultiplePdfs = QtWidgets.QAction(MainWindow)
        self.actionExportMultiplePdfs.setText(QtWidgets.QApplication.translate("MainWindow", "Export to Multiple PDFs...", None))
        self.actionExportMultiplePdfs.setObjectName(_fromUtf8("actionExportMultiplePdfs"))
        self.actionSelectAll = QtWidgets.QAction(MainWindow)
        self.actionSelectAll.setText(QtWidgets.QApplication.translate("MainWindow", "Select All", None))
        self.actionSelectAll.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+A", None))
        self.actionSelectAll.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionSelectAll.setObjectName(_fromUtf8("actionSelectAll"))
        self.actionImportChordPro = QtWidgets.QAction(MainWindow)
        self.actionImportChordPro.setText(QtWidgets.QApplication.translate("MainWindow", "Import From ChordPro...", None))
        self.actionImportChordPro.setObjectName(_fromUtf8("actionImportChordPro"))
        self.actionExportChordPro = QtWidgets.QAction(MainWindow)
        self.actionExportChordPro.setText(QtWidgets.QApplication.translate("MainWindow", "Export To ChordPro...", None))
        self.actionExportChordPro.setObjectName(_fromUtf8("actionExportChordPro"))
        self.actionSetID = QtWidgets.QAction(MainWindow)
        self.actionSetID.setText(QtWidgets.QApplication.translate("MainWindow", "Set Database ID...", None))
        self.actionSetID.setObjectName(_fromUtf8("actionSetID"))
        self.actionCopySongText = QtWidgets.QAction(MainWindow)
        self.actionCopySongText.setText(QtWidgets.QApplication.translate("MainWindow", "Copy Song Text", None))
        self.actionCopySongText.setObjectName(_fromUtf8("actionCopySongText"))
        self.actionPasteAsNewSong = QtWidgets.QAction(MainWindow)
        self.actionPasteAsNewSong.setText(QtWidgets.QApplication.translate("MainWindow", "Paste As New Song", None))
        self.actionPasteAsNewSong.setObjectName(_fromUtf8("actionPasteAsNewSong"))
        self.actionDeleteSongs = QtWidgets.QAction(MainWindow)
        self.actionDeleteSongs.setText(QtWidgets.QApplication.translate("MainWindow", "Delete Selected songs", None))
        self.actionDeleteSongs.setObjectName(_fromUtf8("actionDeleteSongs"))
        self.actionExportSongPDF = QtWidgets.QAction(MainWindow)
        self.actionExportSongPDF.setText(QtWidgets.QApplication.translate("MainWindow", "Export to PDF...", None))
        self.actionExportSongPDF.setObjectName(_fromUtf8("actionExportSongPDF"))
        self.actionExportSinglePdf = QtWidgets.QAction(MainWindow)
        self.actionExportSinglePdf.setText(QtWidgets.QApplication.translate("MainWindow", "Export to PDF...", None))
        self.actionExportSinglePdf.setObjectName(_fromUtf8("actionExportSinglePdf"))
        self.actionImportClipboard = QtWidgets.QAction(MainWindow)
        self.actionImportClipboard.setText(QtWidgets.QApplication.translate("MainWindow", "Import From Clipboard...", None))
        self.actionImportClipboard.setObjectName(_fromUtf8("actionImportClipboard"))
        self.actionExportClipboard = QtWidgets.QAction(MainWindow)
        self.actionExportClipboard.setText(QtWidgets.QApplication.translate("MainWindow", "Export To Clipboard", None))
        self.actionExportClipboard.setObjectName(_fromUtf8("actionExportClipboard"))
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom In", None))
        self.actionZoomIn.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+=", None))
        self.actionZoomIn.setObjectName(_fromUtf8("actionZoomIn"))
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        self.actionZoomOut.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom Out", None))
        self.actionZoomOut.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+-", None))
        self.actionZoomOut.setObjectName(_fromUtf8("actionZoomOut"))
        self.actionZoomActual = QtWidgets.QAction(MainWindow)
        self.actionZoomActual.setText(QtWidgets.QApplication.translate("MainWindow", "Actual Zoom", None))
        self.actionZoomActual.setObjectName(_fromUtf8("actionZoomActual"))
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setText(QtWidgets.QApplication.translate("MainWindow", "Copy", None))
        self.actionCopy.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+C", None))
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setText(QtWidgets.QApplication.translate("MainWindow", "Cut", None))
        self.actionCut.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+X", None))
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setText(QtWidgets.QApplication.translate("MainWindow", "Paste", None))
        self.actionPaste.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+V", None))
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionExportSongToPdf = QtWidgets.QAction(MainWindow)
        self.actionExportSongToPdf.setText(QtWidgets.QApplication.translate("MainWindow", "Export To PDF...", None))
        self.actionExportSongToPdf.setObjectName(_fromUtf8("actionExportSongToPdf"))
        self.actionRemoveTrailingSpaces = QtWidgets.QAction(MainWindow)
        self.actionRemoveTrailingSpaces.setText(QtWidgets.QApplication.translate("MainWindow", "Remove Trailing Spaces", None))
        self.actionRemoveTrailingSpaces.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Remove trailing spaces from every line in the selected song(s)", None))
        self.actionRemoveTrailingSpaces.setObjectName(_fromUtf8("actionRemoveTrailingSpaces"))
        self.actionAppendSongbook = QtWidgets.QAction(MainWindow)
        self.actionAppendSongbook.setText(QtWidgets.QApplication.translate("MainWindow", "Append Another Songbook...", None))
        self.actionAppendSongbook.setObjectName(_fromUtf8("actionAppendSongbook"))
        self.actionRenumberSongs = QtWidgets.QAction(MainWindow)
        self.actionRenumberSongs.setText(QtWidgets.QApplication.translate("MainWindow", "Renumber all songs...", None))
        self.actionRenumberSongs.setObjectName(_fromUtf8("actionRenumberSongs"))
        self.actionChordEditorMode = QtWidgets.QAction(MainWindow)
        self.actionChordEditorMode.setText(QtWidgets.QApplication.translate("MainWindow", "Chord Editor Mode", None))
        self.actionChordEditorMode.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+K", None))
        self.actionChordEditorMode.setObjectName(_fromUtf8("actionChordEditorMode"))
        self.actionLyricEditorMode = QtWidgets.QAction(MainWindow)
        self.actionLyricEditorMode.setText(QtWidgets.QApplication.translate("MainWindow", "Lyric Editor Mode", None))
        self.actionLyricEditorMode.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+L", None))
        self.actionLyricEditorMode.setObjectName(_fromUtf8("actionLyricEditorMode"))
        self.menuSong.addAction(self.actionSetID)
        self.menuSong.addAction(self.actionDeleteSong)
        self.menuSong.addSeparator()
        self.menuSong.addAction(self.actionExportText)
        self.menuSong.addAction(self.actionExportChordPro)
        self.menuSong.addAction(self.actionExportClipboard)
        self.menuSong.addAction(self.actionExportSongToPdf)
        self.menuFile.addAction(self.actionNewSongbook)
        self.menuFile.addAction(self.actionOpenSongbook)
        self.menuFile.addAction(self.actionCloseSongbook)
        self.menuFile.addAction(self.actionSaveSongbook)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImportClipboard)
        self.menuFile.addAction(self.actionImportChordPro)
        self.menuFile.addAction(self.actionImportText)
        self.menuFile.addAction(self.actionAppendSongbook)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportSinglePdf)
        self.menuFile.addAction(self.actionExportMultiplePdfs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuSettings.addAction(self.actionLyricsFont)
        self.menuSettings.addAction(self.actionChordsFont)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionZoomIn)
        self.menuSettings.addAction(self.actionZoomOut)
        self.menuSettings.addAction(self.actionZoomActual)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCopySongText)
        self.menuEdit.addAction(self.actionPasteAsNewSong)
        self.menuEdit.addAction(self.actionSelectAll)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionNewSong)
        self.menuEdit.addAction(self.actionDeleteSongs)
        self.menuEdit.addAction(self.actionRemoveTrailingSpaces)
        self.menuEdit.addAction(self.actionRenumberSongs)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionChordEditorMode)
        self.menuEdit.addAction(self.actionLyricEditorMode)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSong.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

